### Creates a new patient entity
POST http://localhost:4000/patients
Content-Type: application/json

{
  "name" : "John Doe",
  "email" : "John@Doe.com",
  "address": "123 Main Str",
  "dateOfBirth": "1995-09-09",
  "registeredDate": "2026-01-01"
}

###